### ISSUE TITLE
Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by cetindogu** [eBTCCommunityTrustToken/eBTC#1]
powershell window
--------------------------------------------------------------------------------------------------------------
PS C:\_temp\gitprojects> git clone git@github.com:eBTCCommunityTrustToken/eBTC.git
Cloning into 'eBTC'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
PS C:\_temp\gitprojects>

**Comment by purplematter** [comment]
Please try cloning with https.

https://github.com/eBTCCommunityTrustToken/eBTC.git

**Comment by h3ph4est7s** [comment]
fixed https://github.com/eBTCCommunityTrustToken/eBTC/commit/56e0363e6d266ee7aef9a364a57f65980e1ecd1d
