### ISSUE TITLE
EBTC Issue ( 0xeb7c20027172e5d143fb030d50f91cece2d1485d )

### ISSUE THREAD

**Issue by GC2012** [eBTCCommunityTrustToken/eBTC#3]
I was trading EBTC ( the NEW ONE ) traded on the 07/11/2017 on HITBTC. There after I did transfer them to my Ethereum Wallet. 

It seems to be a problem since the product EBTC has no value and this is the NEW EBTC Token. 

![ebtc issue](https://user-images.githubusercontent.com/28044222/32498515-2cfdeac2-c3d0-11e7-9eed-0e643a5b10bd.png)

**Comment by GC2012** [comment]
any thoughts ?

**Comment by ebtctoken** [comment]
value per token on etherscan IS NOT market value of eBTC token, you have to contact etherscan.io when it's shows zero
to see real market value of eBTC token:
https://coinmarketcap.com/currencies/ebtc/#markets

this is not an issue related to eBTC. closed.
